# Generated by Django 4.2 on 2023-04-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_request', '0002_rename_body_logrequest_json_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrequest',
            name='json_body',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
