# Generated by Django 4.2 on 2023-04-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_request', '0003_alter_logrequest_json_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrequest',
            name='sent_headers',
            field=models.JSONField(default=dict),
        ),
    ]
