# Generated by Django 4.2 on 2023-04-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_request', '0004_logrequest_sent_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrequest',
            name='exception_message',
            field=models.TextField(default=None, null=True),
        ),
    ]
